name: "Change Manager"
summary: >-
  The actual project for the change manager role, which is used in the test suite to verify that the change manager role is correctly associated with projects 
  and events. This project is stored in the 'change_manager' subfolder.
externalStatus: ''
internalStatus: ''
lastUpdated: '2026-04-09'